<img src="../Pierian-Data-Logo.PNG">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports

In [1]:
import torch
import numpy as np

### 2. Set the random seed for NumPy and PyTorch both to "42"

In [2]:
torch.manual_seed(42)

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [3]:
arr = [np.random.randint(5) for i in range(6)]
arr

[3, 2, 0, 2, 4, 0]

### 4. Create a tensor "x" from the array above

In [4]:
x = torch.tensor(arr)
x

tensor([3, 2, 0, 2, 4, 0])

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [5]:
x = x.view(3,-1)

### 7. Return the right-hand column of tensor x

In [6]:
x.view(3,-1)[:,1:]

tensor([[2],
        [2],
        [0]])

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [7]:
x.mul(x)

tensor([[ 9,  4],
        [ 0,  4],
        [16,  0]])

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [8]:
y = torch.randint_like(x, 0, 5).reshape(-1,3)
y

tensor([[2, 2, 1],
        [4, 1, 0]])

### 10. Find the matrix product of x and y

In [9]:
# CODE HERE
torch.mm(x,y)

tensor([[14,  8,  3],
        [ 8,  2,  0],
        [ 8,  8,  4]])

## Great job!