# Tensor Operations
This section covers:
* Indexing and slicing
* Reshaping tensors (tensor views)
* Tensor arithmetic and basic operations
* Dot products
* Matrix multiplication
* Additional, more advanced operations

## Perform standard imports

In [1]:
import torch
import numpy as np

## Indexing and slicing
Extracting specific values from a tensor works just the same as with NumPy arrays

In [3]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
x[1,1]

tensor(3)

In [5]:
x[:,1]

tensor([1, 3, 5])

In [8]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

## Reshape tensors with <tt>.view()</tt>
<a href='https://pytorch.org/docs/master/tensors.html#torch.Tensor.view'><strong><tt>view()</tt></strong></a> and <a href='https://pytorch.org/docs/master/torch.html#torch.reshape'><strong><tt>reshape()</tt></strong></a> do essentially the same thing by returning a reshaped tensor without changing the original tensor in place.<br>
There's a good discussion of the differences <a href='https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch'>here</a>.

In [9]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
print(x.view(2,5))
print(x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [13]:
print(x.reshape(2,5))
print(x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Views reflect the most current data

In [14]:
z = x.view(2,5)
x[0] = 9999
print(f'x arr:\n{x}')
print(f'z arr:\n{z}')

x arr:
tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])
z arr:
tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [15]:
x = torch.arange(10)

### Views can infer the correct size
By passing in <tt>-1</tt> PyTorch will infer the correct value from the given tensor

In [16]:
# INFER what the 2nd dimension
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Tensor Arithmetic
Adding tensors can be performed a few different ways depending on the desired result.

In [18]:
a = torch.Tensor([1,2,3])
a

tensor([1., 2., 3.])

In [19]:
b = torch.Tensor([4,5,6])
b

tensor([4., 5., 6.])

In [20]:
a + b

tensor([5., 7., 9.])

In [21]:
torch.add(a,b)

tensor([5., 7., 9.])

In [24]:
# a * b
a.mul(b)
print(f'after a.mul :\n{a}') # a stay the same
# a = a * b
a.mul_(b)
print(f'after a.mul_:\n{a}') # a get reasign

after a.mul :
tensor([ 4., 10., 18.])
after a.mul_:
tensor([ 16.,  50., 108.])


<div class="alert alert-info"><strong>NOTE:</strong> Any operation that changes a tensor in-place is post-fixed with an underscore _.
    <br>In the above example: <tt>a.add_(b)</tt> changed <tt>a</tt>.</div>

In [25]:
a = torch.Tensor([1,2,3])
a

tensor([1., 2., 3.])

## Dot products
A <a href='https://en.wikipedia.org/wiki/Dot_product'>dot product</a> is the sum of the products of the corresponding entries of two 1D tensors. If the tensors are both vectors, the dot product is given as:<br>

$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$

If the tensors include a column vector, then the dot product is the sum of the result of the multiplied matrices. For example:<br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>
Dot products can be expressed as <a href='https://pytorch.org/docs/stable/torch.html#torch.dot'><strong><tt>torch.dot(a,b)</tt></strong></a> or `a.dot(b)` or `b.dot(a)`

In [26]:
a.dot(b)

tensor(32.)

<div class="alert alert-info"><strong>NOTE:</strong> There's a slight difference between <tt>torch.dot()</tt> and <tt>numpy.dot()</tt>. While <tt>torch.dot()</tt> only accepts 1D arguments and returns a dot product, <tt>numpy.dot()</tt> also accepts 2D arguments and performs matrix multiplication. We show matrix multiplication below.</div>

## Matrix multiplication
2D <a href='https://en.wikipedia.org/wiki/Matrix_multiplication'>Matrix multiplication</a> is possible when the number of columns in tensor <strong><tt>A</tt></strong> matches the number of rows in tensor <strong><tt>B</tt></strong>. In this case, the product of tensor <strong><tt>A</tt></strong> with size $(x,y)$ and tensor <strong><tt>B</tt></strong> with size $(y,z)$ results in a tensor of size $(x,z)$
<div>

$\begin{bmatrix} a & b & c \\
d & e & f \end{bmatrix} \;\times\; \begin{bmatrix} m & n \\ p & q \\ r & s \end{bmatrix} = \begin{bmatrix} (am+bp+cr) & (an+bq+cs) \\
(dm+ep+fr) & (dn+eq+fs) \end{bmatrix}$</div></div>
Matrix multiplication can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.mm'><strong><tt>torch.mm(a,b)</tt></strong></a> or `a.mm(b)` or `a @ b`

In [30]:
a = torch.Tensor([[1,2,3],[4,5,6]])
b = torch.Tensor([[7,8],[9,10],[11,12]])

print(f'a: {a}')
print(f'b: {b}')

a: tensor([[1., 2., 3.],
        [4., 5., 6.]])
b: tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [31]:
torch.mm(a,b)

tensor([[ 58.,  64.],
        [139., 154.]])

### Matrix multiplication with broadcasting
Matrix multiplication that involves <a href='https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics'>broadcasting</a> can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.matmul'><strong><tt>torch.matmul(a,b)</tt></strong></a> or `a.matmul(b)` or `a @ b`

In [40]:
t1 = torch.randn(2,4,4)
t2 = torch.randn(4,5)

torch.mm(t1,t2)

RuntimeError: self must be a matrix

In [39]:
t1 = torch.randn(2, 4, 4)
t2 = torch.randn(4, 5)

torch.matmul(t1,t2)

tensor([[[ 6.1431,  2.8203, -2.0512, -3.2533, -4.3642],
         [ 3.4309,  1.1813, -3.9589, -1.3524, -0.5890],
         [-0.4506,  0.9921,  1.6111,  1.7922,  1.0522],
         [ 1.5785,  0.2698,  0.7073,  0.3044, -1.7832]],

        [[-0.5113,  0.3929, -1.0074, -1.1493,  0.9895],
         [-4.0703,  0.1589,  2.6202,  0.3666,  2.7941],
         [ 1.9066, -2.4961, -2.0511,  2.0448, -1.6237],
         [ 2.2026, -1.3199, -2.5710,  1.1377, -1.0649]]])

___
# Advanced operations

## L2 or Euclidian Norm
See <a href='https://pytorch.org/docs/stable/torch.html#torch.norm'><strong><tt>torch.norm()</tt></strong></a>

The <a href='https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm'>Euclidian Norm</a> gives the vector norm of $x$ where $x=(x_1,x_2,...,x_n)$.<br>
It is calculated as<br>

${\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}:={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}}$


When applied to a matrix, <tt>torch.norm()</tt> returns the <a href='https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm'>Frobenius norm</a> by default.

In [42]:
x = torch.Tensor([4,8,3,7])

x.norm()

tensor(11.7473)

## Number of elements
See <a href='https://pytorch.org/docs/stable/torch.html#torch.numel'><strong><tt>torch.numel()</tt></strong></a>

Returns the number of elements in a tensor.

In [43]:
x = torch.ones(3,7)
x

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [44]:
x.numel()

21