# Tensor Basics
This section covers:
* Converting NumPy arrays to PyTorch tensors
* Creating tensors from scratch

## Perform standard imports

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.1.1'

## Converting NumPy arrays to PyTorch tensors
A <a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.Tensor</tt></strong></a> is a multi-dimensional matrix containing elements of a single data type.<br>
Calculations between tensors can only happen if the tensors share the same dtype.<br>
In some cases tensors are used as a replacement for NumPy to use the power of GPUs (more on this later).

In [3]:
arr = np.array(np.arange(1,6))

In [4]:
arr.dtype

dtype('int64')

In [5]:
type(arr)

numpy.ndarray

In [7]:
x = torch.from_numpy(arr)

In [8]:
type(x)

torch.Tensor

In [9]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [10]:
arr2d = np.arange(.0,12)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [11]:
arr2d = arr2d.reshape(4,3)

In [12]:
x2 = torch.as_tensor(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

<a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from_numpy()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_tensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor()</tt></strong></a><br>

There are a number of different functions available for <a href='https://pytorch.org/docs/stable/torch.html#creation-ops'>creating tensors</a>. When using <a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from_numpy()</tt></strong></a> and <a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_tensor()</tt></strong></a>, the PyTorch tensor and the source NumPy array share the same memory. This means that changes to one affect the other. However, the <a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor()</tt></strong></a> function always makes a copy.

In [13]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [14]:
x

tensor([99,  2,  3,  4,  5])

In [23]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_tensor = torch.tensor(my_arr)
tens = torch.as_tensor(my_arr)
my_other_tensor = torch.from_numpy(my_arr)

In [25]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [26]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
tens

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [28]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

## Creating tensors from scratch
### Uninitialized tensors with <tt>.empty()</tt>
<a href='https://pytorch.org/docs/stable/torch.html#torch.empty'><strong><tt>torch.empty()</tt></strong></a> returns an <em>uninitialized</em> tensor. Essentially a block of memory is allocated according to the size of the tensor, and any values already sitting in the block are returned. This is similar to the behavior of <tt>numpy.empty()</tt>.

In [29]:
torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

### Initialized tensors with <tt>.zeros()</tt> and <tt>.ones()</tt>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones'><strong><tt>torch.ones(size)</tt></strong></a><br>
It's a good idea to pass in the intended dtype.

In [32]:
torch.ones(4,3, dtype=int)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

### Tensors from ranges
<a href='https://pytorch.org/docs/stable/torch.html#torch.arange'><strong><tt>torch.arange(start,end,step)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.linspace'><strong><tt>torch.linspace(start,end,steps)</tt></strong></a><br>
Note that with <tt>.arange()</tt>, <tt>end</tt> is exclusive, while with <tt>linspace()</tt>, <tt>end</tt> is inclusive.

In [37]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [38]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [41]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [43]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

### Random number tensors
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand'><strong><tt>torch.rand(size)</tt></strong></a> returns random samples from a uniform distribution over [0, 1)<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn'><strong><tt>torch.randn(size)</tt></strong></a> returns samples from the "standard normal" distribution [σ = 1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;Unlike <tt>rand</tt> which is uniform, values closer to zero are more likely to appear.<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint'><strong><tt>torch.randint(low,high,size)</tt></strong></a> returns random integers from low (inclusive) to high (exclusive)

In [44]:
torch.rand(4,3)

tensor([[0.7664, 0.4217, 0.4393],
        [0.6841, 0.3511, 0.1040],
        [0.2861, 0.4313, 0.8422],
        [0.5351, 0.5381, 0.8497]])

In [45]:
torch.randn(4,3)

tensor([[-0.4094, -1.9861,  1.2946],
        [-0.5562, -0.3325,  1.4248],
        [ 1.3878, -1.0373,  0.1834],
        [-0.6329,  1.5741, -0.1281]])

In [46]:
torch.randint(low=0, high=15, size=(5,5))

tensor([[14,  8, 11,  0,  1],
        [ 2,  6,  3, 13,  5],
        [ 3,  8,  6,  5,  0],
        [ 1,  3,  7,  3,  3],
        [10, 10,  9,  1,  3]])

### Random number tensors that follow the input size
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand_like'><strong><tt>torch.rand_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn_like'><strong><tt>torch.randn_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint_like'><strong><tt>torch.randint_like(input,low,high)</tt></strong></a><br> these return random number tensors with the same size as <tt>input</tt>

In [48]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [49]:
torch.rand_like(x)

tensor([[0.0929, 0.1414, 0.2495, 0.6717, 0.3154],
        [0.7071, 0.1852, 0.8177, 0.3230, 0.9899]])

In [50]:
torch.randn_like(x)

tensor([[-0.5254,  0.6504, -0.9261,  0.3078, -1.1864],
        [ 0.8605, -1.3193,  0.9024, -1.0562, -0.4284]])

In [51]:
torch.randint_like(x, low=0, high=15)

tensor([[ 8.,  7.,  6., 13., 12.],
        [10., 12.,  4.,  8.,  8.]])

### Setting the random seed
<a href='https://pytorch.org/docs/stable/torch.html#torch.manual_seed'><strong><tt>torch.manual_seed(int)</tt></strong></a> is used to obtain reproducible results

In [55]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [56]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [57]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])